name: "Diesel CLI"
description: "Run Diesel CLI in Actions"
inputs:
  migration_directories:
    description: "The list of migration directories to run against"
    required: true
  database_url:
    description: "URL of the database for diesel migrations"
    required: true
    default: test.db
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.migration_directories }}
    - ${{ inputs.database_url }}
